repos:

  # https://github.com/compilerla/conventional-pre-commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: ""
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
