# https://www.richard-banks.org/2018/07/debugging-core-in-docker.html
# https://docs.docker.com/compose/reference/#use--f-to-specify-name-and-path-of-one-or-more-compose-files
# https://docs.docker.com/compose/extends/
# Overrid 'docker-compose.yaml' configs here for debug mode

# To build and debug the app on debug machine --> docker-compose -f docker-compose.yaml -f docker-compose.debug.yml build
# To start and debug the app on debug machine --> docker-compose -f docker-compose.yaml -f docker-compose.debug.yaml up -d

version: "3.8"
services:
  gateway:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    image: gateway:dev
    build:
        target: final
    container_name: gateway-debug
    environment:
        - DOTNET_USE_POLLING_FILE_WATCHER=1
        - ASPNETCORE_ENVIRONMENT=docker
      # https://www.richard-banks.org/2018/07/debugging-core-in-docker.html
      # https://oprea.rocks/blog/how-to-properly-override-the-entrypoint-using-docker-run
      # https://codewithyury.com/docker-run-vs-cmd-vs-entrypoint/
      # https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime
      # https://github.com/microsoft/vscode-docker/issues/3831#issuecomment-1433567030
      # https://docs.docker.com/compose/compose-file/#entrypoint
      ##https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running
      # for debug mode we change entrypoint with '--entrypoint' in 'docker run' for prevent runing application in this stage inner container because we want to run container app with debugger launcher
    entrypoint: /bin/bash
    # https://docs.docker.com/engine/reference/run/#foreground
    # https://www.baeldung.com/ops/docker-compose-interactive-shell#interactive-shell-in-docker-docker-compose-yml-47a72891aee2
    # https://stackoverflow.com/questions/22272401/what-does-it-mean-to-attach-a-tty-std-in-out-to-dockers-or-lxc
    tty: true  # docker run -t
    stdin_open: true # docker run -i

  catalogs:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    image: catalogs:dev
    build:
      target: final
    container_name: catalogs-debug
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=docker
    # https://www.richard-banks.org/2018/07/debugging-core-in-docker.html
    # https://oprea.rocks/blog/how-to-properly-override-the-entrypoint-using-docker-run
    # https://phoenixnap.com/kb/docker-run-override-entrypoint
    # https://codewithyury.com/docker-run-vs-cmd-vs-entrypoint/
    # https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime
    # https://github.com/microsoft/vscode-docker/issues/3831#issuecomment-1433567030
    # https://docs.docker.com/compose/compose-file/#entrypoint
    ##https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running
    # for debug mode we change entrypoint with '--entrypoint' in 'docker run' for prevent runing application in this stage inner container because we want to run container app with debugger launcher
    entrypoint: /bin/bash
    # https://docs.docker.com/engine/reference/run/#foreground
    # https://www.baeldung.com/ops/docker-compose-interactive-shell#interactive-shell-in-docker-docker-compose-yml-47a72891aee2
    # https://stackoverflow.com/questions/22272401/what-does-it-mean-to-attach-a-tty-std-in-out-to-dockers-or-lxc
    tty: true # docker run -t
    stdin_open: true # docker run -i

  identity:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    image: identity:dev
    build:
      target: final
    container_name: identity-debug
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=docker
    # https://www.richard-banks.org/2018/07/debugging-core-in-docker.html
    # https://oprea.rocks/blog/how-to-properly-override-the-entrypoint-using-docker-run
    # https://phoenixnap.com/kb/docker-run-override-entrypoint
    # https://codewithyury.com/docker-run-vs-cmd-vs-entrypoint/
    # https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime
    # https://github.com/microsoft/vscode-docker/issues/3831#issuecomment-1433567030
    # https://docs.docker.com/compose/compose-file/#entrypoint
    ##https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running
    # for debug mode we change entrypoint with '--entrypoint' in 'docker run' for prevent runing application in this stage inner container because we want to run container app with debugger launcher
    entrypoint: /bin/bash
    # https://docs.docker.com/engine/reference/run/#foreground
    # https://www.baeldung.com/ops/docker-compose-interactive-shell#interactive-shell-in-docker-docker-compose-yml-47a72891aee2
    # https://stackoverflow.com/questions/22272401/what-does-it-mean-to-attach-a-tty-std-in-out-to-dockers-or-lxc
    tty: true # docker run -t
    stdin_open: true # docker run -i

  customers:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    image: customers:dev
    build:
      target: final
    container_name: customers-debug
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=docker
    # https://www.richard-banks.org/2018/07/debugging-core-in-docker.html
    # https://oprea.rocks/blog/how-to-properly-override-the-entrypoint-using-docker-run
    # https://phoenixnap.com/kb/docker-run-override-entrypoint
    # https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime
    # https://codewithyury.com/docker-run-vs-cmd-vs-entrypoint/
    # https://github.com/microsoft/vscode-docker/issues/3831#issuecomment-1433567030
    # https://docs.docker.com/compose/compose-file/#entrypointfile/#entrypoint
    ##https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running
    # for debug mode we change entrypoint with '--entrypoint' in 'docker run' for prevent runing application in this stage inner container because we want to run container app with debugger launcher
    entrypoint: /bin/bash
    # https://docs.docker.com/engine/reference/run/#foreground
    # https://www.baeldung.com/ops/docker-compose-interactive-shell#interactive-shell-in-docker-docker-compose-yml-47a72891aee2
    # https://stackoverflow.com/questions/22272401/what-does-it-mean-to-attach-a-tty-std-in-out-to-dockers-or-lxc
    tty: true # docker run -t
    stdin_open: true # docker run -i
