# https://www.trywilco.com/post/wilco-ci-cd-github-heroku
# https://limeii.github.io/2022/11/deploy-on-multiple-environment-with-github-actions/
name: CD

# This action works when creating a tag or release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

# Every push to main will create a new release and deploy to production.
jobs:

  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs(changelog): update changelog'
          file_pattern: CHANGELOG.md

# https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions
# https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

# deploy-development:
#   environment: development
#   needs:
#     - ci-checks
#     - lint
#   runs-on: ubuntu-latest
#   timeout-minutes: 15
#   steps:
#     - uses: actions/checkout@v2
#     - uses: akhileshns/heroku-deploy@v3.12.12
#       with:
#         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#         heroku_app_name: "<your app name here>"
#         heroku_email: "<your email address>"
#         team: "<team name>"
#         dontautocreate: true # do not create the app if it doesn't exist


# deploy-production:
#   environment: production
#   needs:
#     - ci-checks
#     - lint
#     - deploy-development
#   runs-on: ubuntu-latest
#   timeout-minutes: 15
#   steps:
#     - uses: actions/checkout@v2
#     - uses: akhileshns/heroku-deploy@v3.12.12
#       with:
#         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#         heroku_app_name: "<your app name here>"
#         heroku_email: "<your email address>"
#         team: "<team name>"
#         dontautocreate: true # do not create the app if it doesn't exist
