name: Reusable Release Workflow

on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
  # https://stackoverflow.com/questions/73702333/github-actions-reuse-outputs-from-other-reusable-workflows
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      release-version:
        description: "Version"
        value: ${{ jobs.deploy.outputs.release-version }}
jobs:

  deploy:
    name: Release
    runs-on: ubuntu-latest
    #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
    continue-on-error: false

    # Map the job outputs to step outputs
    outputs:
      release-version: ${{ steps.semantic.outputs.semantic_nextrelease_version }}

    steps:

      # https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values
      - name: Job Info
        run: |
          echo "job name is: $GITHUB_JOB"
          echo "branch name is: ${{ github.ref_name }}"

        # https://github.com/cycjimmy/semantic-release-action/issues/6
        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        # https://stackoverflow.com/questions/750172/how-do-i-change-the-author-and-committer-name-email-for-multiple-commits
        # https://github.com/semantic-release/semantic-release/issues/1208
        # https://github.com/orgs/community/discussions/26560
        # https://github.com/semantic-release/semantic-release/blob/b9b5c7689f0acdfdc079c839db0fcf78339745e2/index.js#L92
        ## https://github.com/actions/checkout/issues/439#issuecomment-965968956
        # get latest remote change because sematic-release in `verifyConditions` event checks local branch has latest remote branch changes, for preventing: The local branch `something` is behind the remote one, therefore a new version won't be published.
        # By default checkout@v3, will check branch on ref/SHA that triggered in starting workflow, so if inner a job in the workflow we change HEAD of repository by changing code, subsequent jobs don't get these commits and they get ref/SHA that triggered in starting workflow
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          # Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: create output dir
        run: mkdir -p "output"

        # https://github.com/actions/download-artifact#download-all-artifacts
        # download artifacts without name will download all artifacts
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: dir
        run: ls -R "${{ github.workspace }}/artifacts/build-test-artifacts"

        # https://askubuntu.com/questions/86849/how-to-unzip-a-zip-file-from-the-terminal
      - name: unzip artifacts
        run: |
          unzip "artifacts/build-test-artifacts/test-results.zip" -d "output"

      - name: Ls Output Files
        if: success()
        run: ls -R ${{ github.workspace }}/output

      - name: Call Composite Action release-note
        uses: ./.github/actions/release-note
        id: release-note-step
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}

          # https://stackoverflow.com/questions/69839851/github-actions-copy-git-user-name-and-user-email-from-last-commit
        # This back-merge may failed because of complexity some merge we should continue next step with using if: always()
        # https://github.com/orgs/community/discussions/26560
      - name: Back Merge Release
        if: success()
        run: |
          ./back-merge.sh
